import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  unlinkSync,
  writeFileSync
} from 'node:fs'
import path from 'node:path'
import { absoluteUrl, markdownPathForRoute } from '../app/site-config.mjs'
import { searchVocabulary } from '../app/search-vocabulary.mjs'
import { routeForFile, walkMdx } from './lib/content.mjs'

const root = process.cwd()
const contentDir = path.join(root, 'content')
const publicDir = path.join(root, 'public')
const sectionDir = path.join(publicDir, 'llms-sections')
const checkOnly = process.argv.includes('--check')
const generatedMarkdownMarker = '<!-- Generated by scripts/generate-llms.mjs. Do not edit. -->'

function parsePage(fullPath) {
  const text = readFileSync(fullPath, 'utf8')
  let frontmatter = ''
  let body = text
  if (text.startsWith('---\n')) {
    const end = text.indexOf('\n---', 4)
    if (end !== -1) {
      frontmatter = text.slice(4, end)
      body = text.slice(end + '\n---'.length).replace(/^\r?\n/, '')
    }
  }
  const titleMatch = /^title:\s*(.+?)\s*$/im.exec(frontmatter)
  const descMatch = /^description:\s*(.+?)\s*$/im.exec(frontmatter)
  const stripQuotes = (value) => value.replace(/^["']|["']$/g, '')
  const route = routeForFile(contentDir, fullPath)
  const keywords = vocabularyForRoute(route)

  return {
    title: titleMatch ? stripQuotes(titleMatch[1]) : 'Untitled',
    description: descMatch ? stripQuotes(descMatch[1]) : '',
    keywords,
    updated: extractPageDate(frontmatter, ['updated', 'lastUpdated', 'date']),
    body: sanitizeMdxForLlms(body, route),
    bodyMarkdown: sanitizeMdxForMarkdownMirror(body, route)
  }
}

function propValue(props, name) {
  const match = new RegExp(`${name}\\s*=\\s*(["'])(.*?)\\1`, 's').exec(props)
  return match?.[2]?.trim() ?? ''
}

function renderImageAlt(props, { markdown = false } = {}) {
  const alt = propValue(props, 'alt') || propValue(props, 'aria-label') || propValue(props, 'title')
  if (markdown) {
    const src = propValue(props, 'src') || propValue(props, 'href')
    return src ? `![${alt}](${src})` : alt ? `*${alt}*` : ''
  }
  return alt ? `Image: ${alt}` : ''
}

function stripJsxTags(value, { markdown = false } = {}) {
  return value
    .replace(/<img\s+([^>]*?)\/?>/gi, (_match, props) => renderImageAlt(props, { markdown }))
    .replace(/<Image\s+([^>]*?)\/?>/g, (_match, props) => renderImageAlt(props, { markdown }))
    .replace(/!\[([^\]]*)]\([^)]+\)/g, (match, alt) =>
      markdown ? match : alt ? `Image: ${alt}` : ''
    )
    .replace(/<style[\s\S]*?<\/style>/gi, '')
    .replace(/^\s*(import|export)\s.+$/gm, '')
    .replace(/<svg[\s\S]*?<\/svg>/gi, '')
    .replace(/<(strong|b)>([\s\S]*?)<\/\1>/gi, '**$2**')
    .replace(/<(em|i)>([\s\S]*?)<\/\1>/gi, '*$2*')
    .replace(/<code>([\s\S]*?)<\/code>/gi, '`$1`')
    .replace(/<\/?(?:strong|b|em|i|code|kbd|sup|sub|abbr|mark|small|aside)\b[^>]*>/gi, '')
    .replace(/<[^>\n]+\/>/g, '')
    .replace(/<\/?(?:Steps|Callout|div|span|a|figure|figcaption)[^>]*>/g, '')
    .replace(/<\/?[A-Z][^>]*>/g, '')
    .replace(/<\/?[a-z][^>]*\s(?:class|className|style)=["'][^"']*["'][^>]*>/gi, '')
}

function normalizeTables(value) {
  return value
    .split('\n')
    .map((line) => {
      if (!line.trim().startsWith('|')) return line
      if (/^\|\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?$/.test(line.trim())) return ''
      return line
        .split('|')
        .map((cell) => cell.trim())
        .filter(Boolean)
        .join(' | ')
    })
    .join('\n')
}

function appendVocabulary(body, route) {
  const keywords = vocabularyForRoute(route)
  if (!keywords.length) return body
  return `${body.trim()}\n\nRelevant app/search vocabulary: ${keywords.join(', ')}.`
}

function absolutizeMarkdownLinks(value, route) {
  return value
    .replace(/\]\((#[^)]+)\)/g, (_match, hash) => `](${absoluteUrl(`${route}${hash}`)})`)
    .replace(/\]\((\/[^)\s]+)\)/g, (_match, href) => `](${absoluteUrl(href)})`)
}

function cleanupEntities(value) {
  return value
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/\n{3,}/g, '\n\n')
    .replace(/[ \t]+\n/g, '\n')
    .trim()
}

function sanitizeMdxForLlms(body, route) {
  return cleanupEntities(
    appendVocabulary(absolutizeMarkdownLinks(normalizeTables(stripJsxTags(body)), route), route)
  )
}

// Markdown mirror variant for the human-readable /*.md files: keep real
// ![alt](url) image markdown and omit the appended search-vocabulary line. The
// Image:/vocabulary conventions stay only in the machine llms*.txt bundles.
function sanitizeMdxForMarkdownMirror(body, route) {
  return cleanupEntities(
    absolutizeMarkdownLinks(normalizeTables(stripJsxTags(body, { markdown: true })), route)
  )
}

function checkOrWrite(relativePath, nextContent) {
  const target = path.join(publicDir, relativePath)

  if (!checkOnly) {
    mkdirSync(path.dirname(target), { recursive: true })
    writeFileSync(target, nextContent)
    return null
  }

  if (!existsSync(target)) return `${relativePath} is missing`

  const currentContent = readFileSync(target, 'utf8')
  if (currentContent !== nextContent) return `${relativePath} is stale`

  return null
}

function validateCleanLlmsFull(value) {
  const forbidden = [
    /<style/i,
    /className=/,
    /\bstyle=/,
    /^\s*import\s/m,
    /^\s*export\s/m,
    /<svg[\s>]/i,
    /<\/?(?:strong|em|code)[\s>]/i
  ]
  return forbidden
    .filter((pattern) => pattern.test(value))
    .map((pattern) => `llms-full.txt contains ${pattern}`)
}

const routeVocabulary = searchVocabulary
function vocabularyForRoute(route) {
  const terms = new Set()
  for (const entry of routeVocabulary) {
    if (entry.match.test(route)) {
      for (const term of entry.terms) terms.add(term)
    }
  }
  return [...terms]
}

const monthNumbers = new Map([
  ['january', '01'],
  ['february', '02'],
  ['march', '03'],
  ['april', '04'],
  ['may', '05'],
  ['june', '06'],
  ['july', '07'],
  ['august', '08'],
  ['september', '09'],
  ['october', '10'],
  ['november', '11'],
  ['december', '12']
])

function normalizeDate(value) {
  const iso = /\b(\d{4}-\d{2}-\d{2})\b/.exec(value)
  if (iso) return iso[1]

  const written = /\b([A-Za-z]+)\s+(\d{1,2}),\s+(\d{4})\b/.exec(value)
  if (!written) return null

  const month = monthNumbers.get(written[1].toLowerCase())
  if (!month) return null

  return `${written[3]}-${month}-${written[2].padStart(2, '0')}`
}

function extractPageDate(frontmatter, names) {
  for (const name of names) {
    const frontmatterMatch = new RegExp(`^${name}:\\s*["']?([^"']+)["']?\\s*$`, 'im').exec(
      frontmatter
    )
    if (frontmatterMatch) {
      const date = normalizeDate(frontmatterMatch[1])
      if (date) return date
    }
  }

  return null
}

function markdownRelativePathForRoute(route) {
  return markdownPathForRoute(route).replace(/^\/+/, '')
}

function stripLeadingH1(value) {
  return value.replace(/^#\s+.+(?:\r?\n)+/, '').trim()
}

function generatedPageMarkdown(page) {
  const facts = [
    `Canonical URL: ${absoluteUrl(page.route)}`,
    `Markdown URL: ${absoluteUrl(markdownPathForRoute(page.route))}`,
    `Section: ${sectionTitles[page.section] ?? page.section}`,
    page.updated ? `Updated: ${page.updated}` : ''
  ].filter(Boolean)

  return `${generatedMarkdownMarker}
# ${page.title}

${page.description ? `> ${page.description}\n\n` : ''}${facts.join('\n')}

Documentation index: ${absoluteUrl('/llms.txt')}
Full documentation bundle: ${absoluteUrl('/llms-full.txt')}

---

${stripLeadingH1(page.bodyMarkdown)}
`
}

function removeStaleMarkdownMirrors(expectedRelativePaths) {
  if (checkOnly || !existsSync(publicDir)) return

  const expected = new Set(expectedRelativePaths)

  function visit(dir) {
    for (const entry of readdirSync(dir)) {
      const fullPath = path.join(dir, entry)
      const stat = statSync(fullPath)
      if (stat.isDirectory()) {
        visit(fullPath)
        continue
      }
      if (!entry.endsWith('.md')) continue

      const relativePath = path.relative(publicDir, fullPath).replace(/\\/g, '/')
      if (expected.has(relativePath)) continue

      const text = readFileSync(fullPath, 'utf8')
      if (text.startsWith(generatedMarkdownMarker)) unlinkSync(fullPath)
    }
  }

  visit(publicDir)
}

// Section labels mirror the current primary navigation vocabulary in content/_meta.js.
const sectionTitles = {
  introduction: 'Introduction',
  overview: 'Overview',
  'core-assets': 'Core Assets',
  architecture: 'Core Architecture',
  design: 'Protocol Mechanics',
  testnet: 'Using the Testnet',
  risks: 'Risks'
}
const sectionOrder = Object.keys(sectionTitles)

function sectionForRoute(route) {
  if (route === '/' || route === '/polaris-101') return 'introduction'
  return route.replace(/^\//, '').split('/')[0] || 'overview'
}

function sectionSlug(section) {
  return section.replace(/[^a-z0-9-]/gi, '-').toLowerCase()
}
mkdirSync(publicDir, { recursive: true })
if (!checkOnly) {
  rmSync(sectionDir, { recursive: true, force: true })
}
mkdirSync(sectionDir, { recursive: true })

const pages = walkMdx(contentDir)
  .map((fullPath) => ({
    route: routeForFile(contentDir, fullPath),
    section: sectionForRoute(routeForFile(contentDir, fullPath)),
    ...parsePage(fullPath)
  }))
  .sort((a, b) => a.route.localeCompare(b.route))

const grouped = new Map()
for (const page of pages) {
  if (!grouped.has(page.section)) grouped.set(page.section, [])
  grouped.get(page.section).push(page)
}

const orderedSections = [
  ...sectionOrder.filter((key) => grouped.has(key)),
  ...[...grouped.keys()].filter((key) => !sectionOrder.includes(key)).sort()
]

const header = `# Polaris Documentation

> User documentation for Polaris, an onchain yield layer built around pETH, a yield-bearing reserve asset designed to collateralize censorship-resistant stablecoins and synthetic assets.

## Agent Guidance

- Polaris is currently on the Sepolia public testnet; testnet assets have no monetary value, no production redemption, and no mainnet claim.
- Do not infer production addresses, production constants, audit status, or launch status from testnet values.
- Prefer the Markdown URLs in this file for retrieval, and cite the canonical URL shown beside each page.
`

const pageMarkdownArtifacts = pages.map((page) => ({
  relativePath: markdownRelativePathForRoute(page.route),
  content: generatedPageMarkdown(page),
  page
}))

removeStaleMarkdownMirrors(pageMarkdownArtifacts.map(({ relativePath }) => relativePath))

const sectionArtifacts = orderedSections.map((section) => {
  const heading = sectionTitles[section] ?? section
  const body = grouped
    .get(section)
    .map(
      ({ route, title, body }) =>
        `## ${title}\n\nURL: ${absoluteUrl(route)}\nMarkdown URL: ${absoluteUrl(
          markdownPathForRoute(route)
        )}\n\n${stripLeadingH1(body)}`
    )
    .join('\n\n---\n\n')

  return {
    section,
    title: heading,
    relativePath: `llms-sections/${sectionSlug(section)}.txt`,
    content: `${header}\n# ${heading}\n\n${body}\n`
  }
})

const machineReadableBody = [
  '## Machine-readable artifacts',
  '',
  `- [Complete docs bundle](${absoluteUrl('/llms-full.txt')}): Full sanitized Markdown for every public docs page.`,
  `- [JSON docs index](${absoluteUrl('/llms-index.json')}): Routes, canonical URLs, Markdown URLs, sections, keywords, and freshness metadata.`,
  `- [Well-known llms.txt mirror](${absoluteUrl(
    '/.well-known/llms.txt'
  )}): Alternate discovery path for the docs index.`,
  `- [Well-known full bundle mirror](${absoluteUrl(
    '/.well-known/llms-full.txt'
  )}): Alternate discovery path for the full Markdown bundle.`,
  ...sectionArtifacts.map(
    ({ title, relativePath }) =>
      `- [${title} section bundle](${absoluteUrl(`/${relativePath}`)}): Focused Markdown bundle for this documentation section.`
  )
].join('\n')

const pageIndexBody = orderedSections
  .map((section) => {
    const heading = sectionTitles[section] ?? section
    const lines = grouped
      .get(section)
      .map(({ route, title, description }) => {
        const suffix = description ? `${description} ` : ''
        return `- [${title}](${absoluteUrl(
          markdownPathForRoute(route)
        )}): ${suffix}Canonical: ${absoluteUrl(route)}`
      })
      .join('\n')
    return `## ${heading}\n\n${lines}`
  })
  .join('\n\n')

const indexBody = `${machineReadableBody}\n\n${pageIndexBody}`
const llms = `${header}\n${indexBody}\n`

const fullBody = orderedSections
  .map((section) =>
    grouped
      .get(section)
      .map(
        ({ route, title, body }) =>
          `## ${title}\n\nURL: ${absoluteUrl(route)}\nMarkdown URL: ${absoluteUrl(
            markdownPathForRoute(route)
          )}\n\n${stripLeadingH1(body)}`
      )
      .join('\n\n---\n\n')
  )
  .join('\n\n---\n\n')

const llmsFull = `${header}\n${fullBody}\n`

const llmsIndex = `${JSON.stringify(
  {
    site: absoluteUrl('/'),
    artifacts: {
      llms: absoluteUrl('/llms.txt'),
      llmsFull: absoluteUrl('/llms-full.txt'),
      wellKnownLlms: absoluteUrl('/.well-known/llms.txt'),
      wellKnownLlmsFull: absoluteUrl('/.well-known/llms-full.txt'),
      sections: sectionArtifacts.map(({ title, relativePath }) => ({
        title,
        url: absoluteUrl(`/${relativePath}`)
      }))
    },
    pages: pages.map(({ route, section, title, description, keywords, updated }) => ({
      route,
      url: absoluteUrl(route),
      markdownUrl: absoluteUrl(markdownPathForRoute(route)),
      section: sectionTitles[section] ?? section,
      title,
      description,
      keywords,
      updated
    }))
  },
  null,
  2
)}\n`

const failures = [
  checkOrWrite('llms.txt', llms),
  checkOrWrite('.well-known/llms.txt', llms),
  checkOrWrite('llms-full.txt', llmsFull),
  checkOrWrite('.well-known/llms-full.txt', llmsFull),
  checkOrWrite('llms-index.json', llmsIndex),
  ...pageMarkdownArtifacts.map(({ relativePath, content }) => checkOrWrite(relativePath, content)),
  ...sectionArtifacts.map(({ relativePath, content }) => checkOrWrite(relativePath, content)),
  ...validateCleanLlmsFull(llmsFull)
].filter(Boolean)

if (failures.length) {
  console.error('Generated LLM artifacts are stale or noisy:\n')
  for (const failure of failures) console.error(`- ${failure}`)
  process.exit(1)
}

console.log(
  checkOnly
    ? `LLM artifacts are fresh and clean (${pages.length} pages, ${sectionArtifacts.length} sections).`
    : `Generated llms.txt, llms-full.txt, llms-index.json, and ${sectionArtifacts.length} section files with ${pages.length} pages.`
)
