import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  unlinkSync,
  writeFileSync
} from 'node:fs'
import path from 'node:path'
import {
  LAUNCH_CHAIN_ID,
  LAUNCH_EXPLORER_URL,
  LAUNCH_NETWORK,
  LAUNCH_PHASE,
  timelineCaption,
  timelineSummary
} from '../app/launch-state.mjs'
import { absoluteUrl, markdownPathForRoute } from '../app/site-config.mjs'

const root = process.cwd()
const contentDir = path.join(root, 'content')
const publicDir = path.join(root, 'public')
const sectionDir = path.join(publicDir, 'llms-sections')
const checkOnly = process.argv.includes('--check')
const generatedMarkdownMarker = '<!-- Generated by scripts/generate-llms.mjs. Do not edit. -->'

function walk(dir) {
  const entries = []
  for (const entry of readdirSync(dir)) {
    const fullPath = path.join(dir, entry)
    const stat = statSync(fullPath)
    if (stat.isDirectory()) {
      entries.push(...walk(fullPath))
    } else if (entry.endsWith('.mdx')) {
      entries.push(fullPath)
    }
  }
  return entries
}

function routeForFile(fullPath) {
  const rel = path.relative(contentDir, fullPath).replace(/\\/g, '/')
  const route = rel.replace(/\.mdx$/, '')
  if (route === 'index') return '/'
  if (route.endsWith('/index')) return `/${route.slice(0, -'/index'.length)}`
  return `/${route}`
}

function parsePage(fullPath) {
  const text = readFileSync(fullPath, 'utf8')
  let frontmatter = ''
  let body = text
  if (text.startsWith('---\n')) {
    const end = text.indexOf('\n---', 4)
    if (end !== -1) {
      frontmatter = text.slice(4, end)
      body = text.slice(end + '\n---'.length).replace(/^\r?\n/, '')
    }
  }
  const titleMatch = /^title:\s*(.+?)\s*$/im.exec(frontmatter)
  const descMatch = /^description:\s*(.+?)\s*$/im.exec(frontmatter)
  const stripQuotes = (value) => value.replace(/^["']|["']$/g, '')
  const route = routeForFile(fullPath)
  const keywords = vocabularyForRoute(route)

  return {
    title: titleMatch ? stripQuotes(titleMatch[1]) : 'Untitled',
    description: descMatch ? stripQuotes(descMatch[1]) : '',
    keywords,
    lastVerified: extractPageDate(frontmatter, body, ['lastVerified', 'last_verified']),
    updated: extractPageDate(frontmatter, body, ['updated', 'lastUpdated', 'date']),
    body: sanitizeMdxForLlms(body, route),
    bodyMarkdown: sanitizeMdxForMarkdownMirror(body, route)
  }
}

function propValue(props, name) {
  const match = new RegExp(`${name}\\s*=\\s*(["'])(.*?)\\1`, 's').exec(props)
  return match?.[2]?.trim() ?? ''
}

function renderImageAlt(props, { markdown = false } = {}) {
  const alt = propValue(props, 'alt') || propValue(props, 'aria-label') || propValue(props, 'title')
  if (markdown) {
    const src = propValue(props, 'src') || propValue(props, 'href')
    return src ? `![${alt}](${src})` : alt ? `*${alt}*` : ''
  }
  return alt ? `Image: ${alt}` : ''
}

function linkForLlms(href) {
  if (/^https?:\/\//.test(href)) return href
  if (href.startsWith('/')) return absoluteUrl(href)
  return href
}

function renderNextSteps(props) {
  const stepsBlock = /steps=\{\[([\s\S]*?)\]\}/.exec(props)?.[1] ?? props
  const steps = [
    ...stepsBlock.matchAll(
      /href:\s*(['"])(.*?)\1\s*,\s*title:\s*(['"])(.*?)\3(?:\s*,\s*description:\s*(['"])(.*?)\5)?/g
    )
  ]

  if (!steps.length) return ''

  return [
    'Next steps:',
    ...steps.map((match) => {
      const href = linkForLlms(match[2])
      const title = match[4]
      const description = match[6] ? `: ${match[6]}` : ''
      return `- [${title}](${href})${description}`
    })
  ].join('\n')
}

function stripJsxTags(value, { markdown = false } = {}) {
  const systemOverview =
    'Polaris system overview: ETH swaps into pETH on the bonding curve, pETH collateralizes pAsset markets that issue USDp, and burning pETH for POLAR raises the floor and releases ETH.'
  const timeline = `${timelineSummary()} ${timelineCaption()}`
  return value
    .replace(/<NextSteps\s+([\s\S]*?)\/>/g, (_match, props) => renderNextSteps(props))
    .replace(/<LaunchTimeline\s*\/>/g, markdown ? timeline : `Image: ${timeline}`)
    .replace(/<SystemOverviewFigure\s*\/>/g, markdown ? systemOverview : `Image: ${systemOverview}`)
    .replace(
      /<TimedExplainers\s*\/>/g,
      [
        'Timed explainers:',
        '- [Overview](/explainers/2-min): 2 min read.',
        '- [Presentation](/explainers/5-min): 5 min read.',
        '- [Full Introduction](/explainers/10-min): 10 min read.'
      ].join('\n')
    )
    .replace(/<img\s+([^>]*?)\/?>/gi, (_match, props) => renderImageAlt(props, { markdown }))
    .replace(/<Image\s+([^>]*?)\/?>/g, (_match, props) => renderImageAlt(props, { markdown }))
    .replace(/!\[([^\]]*)]\([^)]+\)/g, (match, alt) =>
      markdown ? match : alt ? `Image: ${alt}` : ''
    )
    .replace(/<style[\s\S]*?<\/style>/gi, '')
    .replace(/^\s*(import|export)\s.+$/gm, '')
    .replace(/<svg[\s\S]*?<\/svg>/gi, '')
    .replace(/<(strong|b)>([\s\S]*?)<\/\1>/gi, '**$2**')
    .replace(/<(em|i)>([\s\S]*?)<\/\1>/gi, '*$2*')
    .replace(/<code>([\s\S]*?)<\/code>/gi, '`$1`')
    .replace(/<\/?(?:strong|b|em|i|code|kbd|sup|sub|abbr|mark|small|aside)\b[^>]*>/gi, '')
    .replace(/<[^>\n]+\/>/g, '')
    .replace(/<\/?(?:Steps|Callout|div|span|a|figure|figcaption)[^>]*>/g, '')
    .replace(/<\/?[A-Z][^>]*>/g, '')
    .replace(/<\/?[a-z][^>]*\s(?:class|className|style)=["'][^"']*["'][^>]*>/gi, '')
}

function normalizeTables(value) {
  return value
    .split('\n')
    .map((line) => {
      if (!line.trim().startsWith('|')) return line
      if (/^\|\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?$/.test(line.trim())) return ''
      return line
        .split('|')
        .map((cell) => cell.trim())
        .filter(Boolean)
        .join(' | ')
    })
    .join('\n')
}

function appendVocabulary(body, route) {
  const keywords = vocabularyForRoute(route)
  if (!keywords.length) return body
  return `${body.trim()}\n\nRelevant app/search vocabulary: ${keywords.join(', ')}.`
}

function absolutizeMarkdownLinks(value, route) {
  return value
    .replace(/\]\((#[^)]+)\)/g, (_match, hash) => `](${absoluteUrl(`${route}${hash}`)})`)
    .replace(/\]\((\/[^)\s]+)\)/g, (_match, href) => `](${absoluteUrl(href)})`)
}

function cleanupEntities(value) {
  return value
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/\n{3,}/g, '\n\n')
    .replace(/[ \t]+\n/g, '\n')
    .trim()
}

function sanitizeMdxForLlms(body, route) {
  return cleanupEntities(
    appendVocabulary(absolutizeMarkdownLinks(normalizeTables(stripJsxTags(body)), route), route)
  )
}

// Markdown mirror variant for the human-readable /*.md files: keep real
// ![alt](url) image markdown and omit the appended search-vocabulary line. The
// Image:/vocabulary conventions stay only in the machine llms*.txt bundles.
function sanitizeMdxForMarkdownMirror(body, route) {
  return cleanupEntities(
    absolutizeMarkdownLinks(normalizeTables(stripJsxTags(body, { markdown: true })), route)
  )
}

function checkOrWrite(relativePath, nextContent) {
  const target = path.join(publicDir, relativePath)

  if (!checkOnly) {
    mkdirSync(path.dirname(target), { recursive: true })
    writeFileSync(target, nextContent)
    return null
  }

  if (!existsSync(target)) return `${relativePath} is missing`

  const currentContent = readFileSync(target, 'utf8')
  if (currentContent !== nextContent) return `${relativePath} is stale`

  return null
}

function validateCleanLlmsFull(value) {
  const forbidden = [
    /<style/i,
    /className=/,
    /\bstyle=/,
    /^\s*import\s/m,
    /^\s*export\s/m,
    /<svg[\s>]/i,
    /<\/?(?:strong|em|code)[\s>]/i
  ]
  return forbidden
    .filter((pattern) => pattern.test(value))
    .map((pattern) => `llms-full.txt contains ${pattern}`)
}

const appPagePath = path.join(root, 'app/[[...mdxPath]]/page.jsx')

function loadRouteVocabulary() {
  const source = readFileSync(appPagePath, 'utf8')
  const match = /const searchVocabulary = (\[[\s\S]*?\])\n\nfunction searchTermsForPath/.exec(
    source
  )

  if (!match) {
    throw new Error('Could not load searchVocabulary from app/[[...mdxPath]]/page.jsx')
  }

  return Function('"use strict"; return (' + match[1] + ');')()
}

const routeVocabulary = loadRouteVocabulary()
function vocabularyForRoute(route) {
  const terms = new Set()
  for (const entry of routeVocabulary) {
    if (entry.match.test(route)) {
      for (const term of entry.terms) terms.add(term)
    }
  }
  return [...terms]
}

const monthNumbers = new Map([
  ['january', '01'],
  ['february', '02'],
  ['march', '03'],
  ['april', '04'],
  ['may', '05'],
  ['june', '06'],
  ['july', '07'],
  ['august', '08'],
  ['september', '09'],
  ['october', '10'],
  ['november', '11'],
  ['december', '12']
])

function normalizeDate(value) {
  const iso = /\b(\d{4}-\d{2}-\d{2})\b/.exec(value)
  if (iso) return iso[1]

  const written = /\b([A-Za-z]+)\s+(\d{1,2}),\s+(\d{4})\b/.exec(value)
  if (!written) return null

  const month = monthNumbers.get(written[1].toLowerCase())
  if (!month) return null

  return `${written[3]}-${month}-${written[2].padStart(2, '0')}`
}

function extractPageDate(frontmatter, body, names) {
  for (const name of names) {
    const frontmatterMatch = new RegExp(`^${name}:\\s*["']?([^"']+)["']?\\s*$`, 'im').exec(
      frontmatter
    )
    if (frontmatterMatch) {
      const date = normalizeDate(frontmatterMatch[1])
      if (date) return date
    }
  }

  if (names.some((name) => /updated|verified|modified/i.test(name))) {
    const bannerMatch = /<PageStatusBanner\s+lastUpdated=(["'])(.*?)\1\s*\/>/i.exec(body)
    if (bannerMatch) {
      const date = normalizeDate(bannerMatch[2])
      if (date) return date
    }
  }

  if (names.some((name) => /last[_-]?verified/i.test(name))) {
    const bodyMatch = /\*\*Last verified:\*\*\s*([^.\n]+)/i.exec(body)
    if (bodyMatch) return normalizeDate(bodyMatch[1])
  }

  return null
}

function markdownRelativePathForRoute(route) {
  return markdownPathForRoute(route).replace(/^\/+/, '')
}

function stripLeadingH1(value) {
  return value.replace(/^#\s+.+(?:\r?\n)+/, '').trim()
}

function generatedPageMarkdown(page) {
  const facts = [
    `Canonical URL: ${absoluteUrl(page.route)}`,
    `Markdown URL: ${absoluteUrl(markdownPathForRoute(page.route))}`,
    `Section: ${sectionTitles[page.section] ?? page.section}`,
    page.updated ? `Updated: ${page.updated}` : '',
    page.lastVerified ? `Last verified: ${page.lastVerified}` : ''
  ].filter(Boolean)

  return `${generatedMarkdownMarker}
# ${page.title}

${page.description ? `> ${page.description}\n\n` : ''}${facts.join('\n')}

Documentation index: ${absoluteUrl('/llms.txt')}
Full documentation bundle: ${absoluteUrl('/llms-full.txt')}

---

${stripLeadingH1(page.bodyMarkdown)}
`
}

function removeStaleMarkdownMirrors(expectedRelativePaths) {
  if (checkOnly || !existsSync(publicDir)) return

  const expected = new Set(expectedRelativePaths)

  function visit(dir) {
    for (const entry of readdirSync(dir)) {
      const fullPath = path.join(dir, entry)
      const stat = statSync(fullPath)
      if (stat.isDirectory()) {
        visit(fullPath)
        continue
      }
      if (!entry.endsWith('.md')) continue

      const relativePath = path.relative(publicDir, fullPath).replace(/\\/g, '/')
      if (expected.has(relativePath)) continue

      const text = readFileSync(fullPath, 'utf8')
      if (text.startsWith(generatedMarkdownMarker)) unlinkSync(fullPath)
    }
  }

  visit(publicDir)
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function stripInlineMarkdown(value) {
  return value
    .replace(/\[([^\]]+)]\([^)]+\)/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/\*([^*]+)\*/g, '$1')
    .replace(/<[^>]+>/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

function parseMarkdownTable(line) {
  return line
    .trim()
    .replace(/^\|/, '')
    .replace(/\|$/, '')
    .split('|')
    .map((cell) => cell.trim())
}

function isSeparatorRow(cells) {
  return cells.every((cell) => /^:?-{3,}:?$/.test(cell))
}

function tableAfterHeading(source, heading) {
  const lines = source.split(/\r?\n/)
  const headingPattern = new RegExp(`^#{2,6}\\s+${escapeRegExp(heading)}\\s*$`, 'i')
  const start = lines.findIndex((line) => headingPattern.test(line.trim()))
  if (start === -1) return []

  const tableStart = lines.findIndex((line, index) => index > start && line.trim().startsWith('|'))
  if (tableStart === -1) return []

  const tableLines = []
  for (let index = tableStart; index < lines.length; index += 1) {
    const line = lines[index]
    if (!line.trim().startsWith('|')) break
    tableLines.push(line)
  }

  if (tableLines.length < 2) return []

  const headers = parseMarkdownTable(tableLines[0]).map(stripInlineMarkdown)
  return tableLines
    .slice(1)
    .map(parseMarkdownTable)
    .filter((cells) => !isSeparatorRow(cells))
    .map((cells) =>
      Object.fromEntries(headers.map((header, index) => [header, cells[index]?.trim() ?? '']))
    )
}

function tableAfterAnyHeading(source, headings) {
  for (const heading of headings) {
    const rows = tableAfterHeading(source, heading)
    if (rows.length) return rows
  }
  return []
}

function firstAddress(value) {
  return /\b0x[a-fA-F0-9]{40}\b/.exec(value)?.[0]?.toLowerCase() ?? null
}

function firstMarkdownUrl(value) {
  return /\]\(([^)]+)\)/.exec(value)?.[1] ?? null
}

function integerFrom(value) {
  const match = /\b\d+\b/.exec(stripInlineMarkdown(value))
  return match ? Number(match[0]) : null
}

function contractEntries(rows, group) {
  return rows
    .map((row) => {
      const rawAddress = row['Sepolia address'] ?? ''
      const address = firstAddress(rawAddress)
      if (!address) return null
      return {
        group,
        name: stripInlineMarkdown(row.Contract ?? ''),
        address,
        explorerUrl: firstMarkdownUrl(rawAddress) ?? `${LAUNCH_EXPLORER_URL}/address/${address}`
      }
    })
    .filter(Boolean)
}

function buildProtocolManifest(pages) {
  const page = pages.find(({ route }) => route === '/resources/testnet')
  if (!page) return null

  const source = readFileSync(path.join(contentDir, 'resources/testnet.mdx'), 'utf8')
  const environmentRows = tableAfterHeading(source, 'Environment')
  const environment = Object.fromEntries(
    environmentRows.map((row) => [
      stripInlineMarkdown(row.Fact ?? ''),
      stripInlineMarkdown(row.Value ?? '')
    ])
  )

  const sharedCoreRows = tableAfterHeading(source, 'Shared core parameters')
  const pAssetRows = tableAfterAnyHeading(source, [
    'pAsset market parameters',
    'pAsset branch parameters'
  ])
  const productionRows = tableAfterHeading(source, 'Production addresses')
  const lastVerified = normalizeDate(environment['Last verified'] ?? '') ?? page.lastVerified

  const sharedCoreParameters = sharedCoreRows.map((row) => ({
    name: stripInlineMarkdown(row.Parameter ?? ''),
    value: stripInlineMarkdown(row[`${LAUNCH_PHASE} value`] ?? ''),
    source: stripInlineMarkdown(row.Source ?? '')
  }))

  const assetNames = Object.keys(pAssetRows[0] ?? {}).filter(
    (key) => key !== 'Parameter' && key !== 'Source'
  )
  const pAssetParameters = Object.fromEntries(
    assetNames.map((asset) => [
      asset,
      pAssetRows.map((row) => ({
        name: stripInlineMarkdown(row.Parameter ?? ''),
        value: stripInlineMarkdown(row[asset] ?? ''),
        source: stripInlineMarkdown(row.Source ?? '')
      }))
    ])
  )

  const contracts = [
    ...contractEntries(tableAfterHeading(source, 'Shared core'), 'shared-core'),
    ...contractEntries(
      tableAfterAnyHeading(source, ['USDp market', 'pUSD market', 'pUSD branch']),
      'pusd-branch'
    ),
    ...contractEntries(
      tableAfterAnyHeading(source, ['GOLDp market', 'pGOLD market', 'pGOLD branch']),
      'pgold-branch'
    )
  ]

  const production = productionRows.map((row) => ({
    network: stripInlineMarkdown(row.Network ?? ''),
    chainId: integerFrom(row.Network ?? ''),
    status: stripInlineMarkdown(row.Status ?? '')
  }))

  return {
    schemaVersion: 1,
    site: absoluteUrl('/'),
    source: {
      route: page.route,
      url: absoluteUrl(page.route),
      markdownUrl: absoluteUrl(markdownPathForRoute(page.route)),
      lastVerified
    },
    status: {
      publicPhase: environment['Public phase'] ?? '',
      productionFinality: environment['Production finality'] ?? ''
    },
    environment: {
      network: environment.Network ?? '',
      chainId: integerFrom(environment['Chain ID'] ?? ''),
      officialApp: environment['Official app'] ?? '',
      testnetValue: environment['Testnet value'] ?? '',
      testnetGas: environment['Testnet gas'] ?? '',
      reserveToken: environment['Reserve token'] ?? '',
      activePassets: environment['Active pAssets'] ?? ''
    },
    warnings: [
      `${LAUNCH_PHASE} values are ${LAUNCH_NETWORK} testnet artifacts.`,
      'Testnet assets have no monetary value, no production redemption, and no mainnet claim.',
      'Do not infer production constants, addresses, audit status, or launch status from testnet values.',
      `Use Launch Status and ${LAUNCH_PHASE} as the canonical sources before signing transactions.`
    ],
    parameters: {
      sharedCore: sharedCoreParameters,
      pAssets: pAssetParameters
    },
    contracts: {
      network: LAUNCH_NETWORK,
      chainId: LAUNCH_CHAIN_ID,
      explorer: LAUNCH_EXPLORER_URL,
      entries: contracts
    },
    production
  }
}

// Section labels mirror the current primary navigation vocabulary in content/_meta.js.
const sectionTitles = {
  introduction: 'Introduction',
  'launch-status': 'Launch Status',
  quickstart: 'Public Testnet Quickstart',
  'using-app': 'Use Polaris',
  troubleshooting: 'Troubleshooting',
  'understand-polaris': 'Understand Polaris',
  resources: 'Reference'
}
const sectionOrder = Object.keys(sectionTitles)

function sectionForRoute(route) {
  if (route === '/') return 'introduction'
  if (route === '/launch-status') return 'launch-status'
  if (route === '/quickstart') return 'quickstart'
  if (route === '/troubleshooting') return 'troubleshooting'
  if (/^\/using-app(?:\/|$)/.test(route)) return 'using-app'
  if (/^\/resources(?:\/|$)/.test(route)) return 'resources'
  if (
    /^\/(?:why-polaris|peth|minting|yield|redemptions-liquidations|polar|stewardship)(?:\/|$)/.test(
      route
    )
  ) {
    return 'understand-polaris'
  }

  return route.replace(/^\//, '').split('/')[0] || 'introduction'
}

function sectionSlug(section) {
  return section.replace(/[^a-z0-9-]/gi, '-').toLowerCase()
}
mkdirSync(publicDir, { recursive: true })
if (!checkOnly) {
  rmSync(sectionDir, { recursive: true, force: true })
}
mkdirSync(sectionDir, { recursive: true })

const pages = walk(contentDir)
  .map((fullPath) => ({
    route: routeForFile(fullPath),
    section: sectionForRoute(routeForFile(fullPath)),
    ...parsePage(fullPath)
  }))
  .sort((a, b) => a.route.localeCompare(b.route))

const grouped = new Map()
for (const page of pages) {
  if (!grouped.has(page.section)) grouped.set(page.section, [])
  grouped.get(page.section).push(page)
}

const orderedSections = [
  ...sectionOrder.filter((key) => grouped.has(key)),
  ...[...grouped.keys()].filter((key) => !sectionOrder.includes(key)).sort()
]

const header = `# Polaris Documentation

> User and developer documentation for Polaris, the pETH-powered yield layer for DeFi. Issue pAssets backed entirely by onchain collateral and yield. No T-bills. No CEXs. No compromises.

## Agent Guidance

- Start with [Launch Status](${absoluteUrl('/launch-status')}) for what is live, supported, or production-final.
- Treat [${LAUNCH_PHASE}](${absoluteUrl('/resources/testnet')}) as the source of truth for ${LAUNCH_NETWORK} network, parameter, and contract-address values.
- ${LAUNCH_PHASE} assets are ${LAUNCH_NETWORK} test assets with no monetary value, no production redemption, and no mainnet claim.
- Do not infer production addresses, production constants, audit status, or launch status from testnet values.
- Prefer the Markdown URLs in this file for retrieval, and cite the canonical URL shown beside each page.
`

const pageMarkdownArtifacts = pages.map((page) => ({
  relativePath: markdownRelativePathForRoute(page.route),
  content: generatedPageMarkdown(page),
  page
}))

removeStaleMarkdownMirrors(pageMarkdownArtifacts.map(({ relativePath }) => relativePath))

const sectionArtifacts = orderedSections.map((section) => {
  const heading = sectionTitles[section] ?? section
  const body = grouped
    .get(section)
    .map(
      ({ route, title, body }) =>
        `## ${title}\n\nURL: ${absoluteUrl(route)}\nMarkdown URL: ${absoluteUrl(
          markdownPathForRoute(route)
        )}\n\n${stripLeadingH1(body)}`
    )
    .join('\n\n---\n\n')

  return {
    section,
    title: heading,
    relativePath: `llms-sections/${sectionSlug(section)}.txt`,
    content: `${header}\n# ${heading}\n\n${body}\n`
  }
})

const machineReadableBody = [
  '## Machine-readable artifacts',
  '',
  `- [Complete docs bundle](${absoluteUrl('/llms-full.txt')}): Full sanitized Markdown for every public docs page.`,
  `- [JSON docs index](${absoluteUrl('/llms-index.json')}): Routes, canonical URLs, Markdown URLs, sections, keywords, and freshness metadata.`,
  `- [Polaris testnet manifest](${absoluteUrl(
    '/polaris-testnet-manifest.json'
  )}): Machine-readable ${LAUNCH_PHASE} environment, parameters, contracts, and warnings.`,
  `- [Well-known llms.txt mirror](${absoluteUrl(
    '/.well-known/llms.txt'
  )}): Alternate discovery path for the docs index.`,
  `- [Well-known full bundle mirror](${absoluteUrl(
    '/.well-known/llms-full.txt'
  )}): Alternate discovery path for the full Markdown bundle.`,
  ...sectionArtifacts.map(
    ({ title, relativePath }) =>
      `- [${title} section bundle](${absoluteUrl(`/${relativePath}`)}): Focused Markdown bundle for this documentation section.`
  )
].join('\n')

const pageIndexBody = orderedSections
  .map((section) => {
    const heading = sectionTitles[section] ?? section
    const lines = grouped
      .get(section)
      .map(({ route, title, description }) => {
        const suffix = description ? `${description} ` : ''
        return `- [${title}](${absoluteUrl(
          markdownPathForRoute(route)
        )}): ${suffix}Canonical: ${absoluteUrl(route)}`
      })
      .join('\n')
    return `## ${heading}\n\n${lines}`
  })
  .join('\n\n')

const indexBody = `${machineReadableBody}\n\n${pageIndexBody}`
const llms = `${header}\n${indexBody}\n`

const fullBody = orderedSections
  .map((section) =>
    grouped
      .get(section)
      .map(
        ({ route, title, body }) =>
          `## ${title}\n\nURL: ${absoluteUrl(route)}\nMarkdown URL: ${absoluteUrl(
            markdownPathForRoute(route)
          )}\n\n${stripLeadingH1(body)}`
      )
      .join('\n\n---\n\n')
  )
  .join('\n\n---\n\n')

const llmsFull = `${header}\n${fullBody}\n`

const llmsIndex = `${JSON.stringify(
  {
    site: absoluteUrl('/'),
    artifacts: {
      llms: absoluteUrl('/llms.txt'),
      llmsFull: absoluteUrl('/llms-full.txt'),
      wellKnownLlms: absoluteUrl('/.well-known/llms.txt'),
      wellKnownLlmsFull: absoluteUrl('/.well-known/llms-full.txt'),
      protocolManifest: absoluteUrl('/polaris-testnet-manifest.json'),
      sections: sectionArtifacts.map(({ title, relativePath }) => ({
        title,
        url: absoluteUrl(`/${relativePath}`)
      }))
    },
    pages: pages.map(({ route, section, title, description, keywords, updated, lastVerified }) => ({
      route,
      url: absoluteUrl(route),
      markdownUrl: absoluteUrl(markdownPathForRoute(route)),
      section: sectionTitles[section] ?? section,
      title,
      description,
      keywords,
      updated,
      lastVerified
    }))
  },
  null,
  2
)}\n`

const protocolManifest = `${JSON.stringify(buildProtocolManifest(pages), null, 2)}\n`

const failures = [
  checkOrWrite('llms.txt', llms),
  checkOrWrite('.well-known/llms.txt', llms),
  checkOrWrite('llms-full.txt', llmsFull),
  checkOrWrite('.well-known/llms-full.txt', llmsFull),
  checkOrWrite('llms-index.json', llmsIndex),
  checkOrWrite('polaris-testnet-manifest.json', protocolManifest),
  ...pageMarkdownArtifacts.map(({ relativePath, content }) => checkOrWrite(relativePath, content)),
  ...sectionArtifacts.map(({ relativePath, content }) => checkOrWrite(relativePath, content)),
  ...validateCleanLlmsFull(llmsFull)
].filter(Boolean)

if (failures.length) {
  console.error('Generated LLM artifacts are stale or noisy:\n')
  for (const failure of failures) console.error(`- ${failure}`)
  process.exit(1)
}

console.log(
  checkOnly
    ? `LLM artifacts are fresh and clean (${pages.length} pages, ${sectionArtifacts.length} sections).`
    : `Generated llms.txt, llms-full.txt, llms-index.json, and ${sectionArtifacts.length} section files with ${pages.length} pages.`
)
