#!/usr/bin/env python3
"""Import Google Docs DOCX review exports back into content/**/*.mdx.

The importer relies on the block markers and _manifest.json generated by
scripts/export-gdocs-review.py. It is intentionally conservative: locked blocks
are restored from source, unchanged editable blocks are restored byte-for-byte,
and stale source files fail unless explicitly allowed.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import re
import sys
import zipfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from xml.etree import ElementTree as ET


ROOT = Path.cwd()
CONTENT_DIR = ROOT / "content"
WORD_NS = "{http://schemas.openxmlformats.org/wordprocessingml/2006/main}"
BLOCK_MARKERS = [
    re.compile(r"^\[\[POLARIS\s+([^\s\]]+)\s+([^\s\]]+)\s+([^\s\]]+)\]\]$"),
    re.compile(
        r"^\[\[POLARIS:BLOCK\s+id=([^\s]+)\s+mode=([^\s]+)\s+type=([^\s\]]+)\]\]$"
    ),
]


@dataclass
class ImportedBlock:
    id: str
    mode: str
    type: str
    elements: list[dict[str, Any]]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Import edited Google Docs DOCX files into content/**/*.mdx."
    )
    parser.add_argument(
        "--zip",
        required=True,
        help="Google Drive DOCX export zip, or a directory containing exported DOCX files.",
    )
    parser.add_argument(
        "--manifest",
        default=None,
        help="Path to _manifest.json from the matching export. Defaults to <zip-dir>/_manifest.json.",
    )
    parser.add_argument(
        "--out",
        default=str(CONTENT_DIR),
        help="Output content directory. Default: content",
    )
    parser.add_argument("--dry-run", action="store_true", help="Report changes without writing files.")
    parser.add_argument(
        "--allow-stale-source",
        action="store_true",
        help="Allow importing when the target source file hash no longer matches the export manifest.",
    )
    parser.add_argument(
        "--report",
        default=None,
        help="Optional path for a JSON import report. Defaults to <manifest-dir>/_import-report.json.",
    )
    return parser.parse_args()


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf8")).hexdigest()


def normalize_text(value: str) -> str:
    return re.sub(r"\s+", " ", value.replace("\xa0", " ")).strip()


def normalize_rows(rows: list[list[str]]) -> list[list[str]]:
    return [[normalize_text(cell) for cell in row] for row in rows]


def read_manifest(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf8"))
    if payload.get("version") != 1 or not isinstance(payload.get("pages"), list):
        raise ValueError(f"Unsupported manifest format: {path}")
    return payload


def default_manifest_path(zip_path: Path) -> Path:
    if zip_path.is_dir():
        return zip_path / "_manifest.json"
    return zip_path.parent / "_manifest.json"


def list_docx_from_directory(directory: Path) -> dict[str, Path]:
    return {
        path.relative_to(directory).as_posix(): path
        for path in directory.rglob("*.docx")
        if not path.name.startswith("~$")
    }


def read_docx_bytes_from_directory(directory: Path, relative_docx: str) -> bytes | None:
    docx_files = list_docx_from_directory(directory)
    match = match_docx_path(docx_files.keys(), relative_docx)
    return docx_files[match].read_bytes() if match else None


def read_docx_bytes_from_zip(zip_path: Path, relative_docx: str) -> bytes | None:
    with zipfile.ZipFile(zip_path) as archive:
        docx_names = [name for name in archive.namelist() if name.endswith(".docx")]
        match = match_docx_path(docx_names, relative_docx)
        return archive.read(match) if match else None


def match_docx_path(candidates: list[str] | Any, relative_docx: str) -> str | None:
    normalized = [candidate.replace("\\", "/") for candidate in candidates]
    if relative_docx in normalized:
        return relative_docx

    first_segments = {candidate.split("/", 1)[0] for candidate in normalized if "/" in candidate}
    if len(first_segments) == 1:
        stripped_matches = [
            candidate for candidate in normalized if candidate.split("/", 1)[1] == relative_docx
        ]
        if len(stripped_matches) == 1:
            return stripped_matches[0]

    suffix = f"/{relative_docx}"
    suffix_matches = [candidate for candidate in normalized if candidate.endswith(suffix)]
    if len(suffix_matches) == 1:
        return suffix_matches[0]

    basename_matches = [candidate for candidate in normalized if Path(candidate).name == Path(relative_docx).name]
    return basename_matches[0] if len(basename_matches) == 1 else None


def read_docx_bytes(zip_or_dir: Path, relative_docx: str) -> bytes | None:
    if zip_or_dir.is_dir():
        return read_docx_bytes_from_directory(zip_or_dir, relative_docx)
    return read_docx_bytes_from_zip(zip_or_dir, relative_docx)


def paragraph_text(paragraph: ET.Element, *, markdown: bool = False) -> str:
    pieces: list[str] = []
    for run in paragraph.findall(f".//{WORD_NS}r"):
        text = run_text(run)
        if not text:
            continue
        if markdown:
            text = wrap_run_markdown(run, text)
        pieces.append(text)
    return "".join(pieces).replace("\xa0", " ").strip()


def run_text(run: ET.Element) -> str:
    pieces: list[str] = []
    for child in run:
        if child.tag == f"{WORD_NS}t":
            pieces.append(child.text or "")
        elif child.tag == f"{WORD_NS}tab":
            pieces.append("\t")
        elif child.tag == f"{WORD_NS}br":
            pieces.append("\n")
    return "".join(pieces)


def has_run_property(run: ET.Element, property_name: str) -> bool:
    rpr = run.find(f"{WORD_NS}rPr")
    return rpr is not None and rpr.find(f"{WORD_NS}{property_name}") is not None


def run_style(run: ET.Element) -> str:
    rpr = run.find(f"{WORD_NS}rPr")
    if rpr is None:
        return ""
    style = rpr.find(f"{WORD_NS}rStyle")
    return style.attrib.get(f"{WORD_NS}val", "") if style is not None else ""


def wrap_run_markdown(run: ET.Element, text: str) -> str:
    if run_style(run) == "CodeChar":
        return f"`{text}`"
    if has_run_property(run, "b"):
        text = f"**{text}**"
    if has_run_property(run, "i"):
        text = f"*{text}*"
    return text


def table_rows(table: ET.Element) -> list[list[str]]:
    rows: list[list[str]] = []
    for tr in table.findall(f"{WORD_NS}tr"):
        row: list[str] = []
        for tc in tr.findall(f"{WORD_NS}tc"):
            cell_paragraphs = [
                paragraph_text(paragraph)
                for paragraph in tc.findall(f"{WORD_NS}p")
                if paragraph_text(paragraph)
            ]
            row.append(" ".join(cell_paragraphs).strip())
        rows.append(row)
    return rows


def parse_block_marker(text: str) -> tuple[str, str, str] | None:
    for pattern in BLOCK_MARKERS:
        marker = pattern.match(text)
        if marker:
            return marker.group(1), marker.group(2), marker.group(3)
    return None


def parse_docx_blocks(docx_bytes: bytes) -> list[ImportedBlock]:
    with zipfile.ZipFile(io.BytesIO(docx_bytes)) as archive:
        document_xml = archive.read("word/document.xml")

    root = ET.fromstring(document_xml)
    body = root.find(f"{WORD_NS}body")
    if body is None:
        return []

    blocks: list[ImportedBlock] = []
    current: ImportedBlock | None = None

    for child in body:
        if child.tag == f"{WORD_NS}p":
            text = paragraph_text(child)
            marker = parse_block_marker(text)
            if marker:
                current = ImportedBlock(
                    id=marker[0],
                    mode=marker[1],
                    type=marker[2],
                    elements=[],
                )
                blocks.append(current)
                continue

            if current is not None and text:
                current.elements.append(
                    {
                        "kind": "paragraph",
                        "text": text,
                        "markdown": paragraph_text(child, markdown=True),
                    }
                )
        elif child.tag == f"{WORD_NS}tbl" and current is not None:
            current.elements.append({"kind": "table", "rows": table_rows(child)})

    return blocks


def source_prefix_and_body(text: str) -> tuple[str, str]:
    if not text.startswith("---\n"):
        return "", text
    end = text.find("\n---", 4)
    if end == -1:
        return "", text
    close_end = end + len("\n---")
    newline_match = re.match(r"(?:\r?\n)+", text[close_end:])
    body_start = close_end + (len(newline_match.group(0)) if newline_match else 0)
    return text[:body_start], text[body_start:]


def imported_plain_text(imported: ImportedBlock) -> str:
    if imported.type == "table":
        for element in imported.elements:
            if element["kind"] == "table":
                return "\n".join(" | ".join(row) for row in element["rows"])
        return ""
    return "\n".join(
        element["text"] for element in imported.elements if element["kind"] == "paragraph"
    ).strip()


def imported_markdown_text(imported: ImportedBlock) -> str:
    return "\n".join(
        element["markdown"] for element in imported.elements if element["kind"] == "paragraph"
    ).strip()


def imported_rows(imported: ImportedBlock) -> list[list[str]]:
    for element in imported.elements:
        if element["kind"] == "table":
            return element["rows"]
    return []


def markdown_table(rows: list[list[str]]) -> str:
    if not rows:
        return ""
    width = max(len(row) for row in rows)
    normalized = [row + [""] * (width - len(row)) for row in rows]
    header = normalized[0]
    separator = ["---"] * width
    body = normalized[1:]
    lines = [
        "| " + " | ".join(header) + " |",
        "| " + " | ".join(separator) + " |",
    ]
    lines.extend("| " + " | ".join(row) + " |" for row in body)
    return "\n".join(lines)


def serialize_changed_block(block: dict[str, Any], imported: ImportedBlock) -> str:
    block_type = block["type"]
    if block_type == "heading":
        text = imported_plain_text(imported)
        level = int(block.get("level") or 2)
        return f"{'#' * level} {text}".strip()

    if block_type == "quote":
        text = imported_markdown_text(imported)
        return "\n".join(f"> {line}" if line else ">" for line in text.splitlines())

    if block_type == "list":
        lines = [line.strip() for line in imported_markdown_text(imported).splitlines() if line.strip()]
        return "\n".join(line if re.match(r"^(?:[-*]|\d+\.)\s+", line) else f"- {line}" for line in lines)

    if block_type == "table":
        return markdown_table(imported_rows(imported))

    text = imported_markdown_text(imported)
    return "\n\n".join(line.strip() for line in text.splitlines() if line.strip())


def count_raw_structures(raw: str) -> dict[str, int]:
    return {
        "links": len(re.findall(r"\[[^\]]+]\([^)]+\)", raw)),
        "tables": 1 if re.search(r"^\|.+\|\s*$", raw, flags=re.MULTILINE) else 0,
        "code": len(re.findall(r"^```", raw, flags=re.MULTILINE)) // 2,
        "headings": len(re.findall(r"^#{1,6}\s+", raw, flags=re.MULTILINE)),
        "list_items": len(re.findall(r"^(?:[-*]|\d+\.)\s+", raw, flags=re.MULTILINE)),
    }


def reconstruct_page(
    page: dict[str, Any], imported_blocks: list[ImportedBlock], current_source: str
) -> tuple[str, dict[str, Any]]:
    imported_by_id = {block.id: block for block in imported_blocks}
    prefix, _body = source_prefix_and_body(current_source)
    output_parts: list[str] = []
    changed_blocks: list[dict[str, Any]] = []
    missing_markers: list[str] = []
    restored_locked = 0

    for block in page["blocks"]:
        imported = imported_by_id.get(block["id"])
        if imported is None:
            missing_markers.append(block["id"])
            output_parts.append(block["raw"] + block.get("separator", ""))
            continue

        if block["mode"] == "locked":
            restored_locked += 1
            output_parts.append(block["raw"] + block.get("separator", ""))
            continue

        if block["type"] == "table":
            unchanged = normalize_rows(imported_rows(imported)) == normalize_rows(block.get("rows") or [])
        else:
            unchanged = normalize_text(imported_plain_text(imported)) == normalize_text(block["text"])

        if unchanged:
            output_parts.append(block["raw"] + block.get("separator", ""))
            continue

        next_raw = serialize_changed_block(block, imported)
        before_counts = count_raw_structures(block["raw"])
        after_counts = count_raw_structures(next_raw)
        changed_blocks.append(
            {
                "id": block["id"],
                "type": block["type"],
                "before": block["text"],
                "after": imported_plain_text(imported),
                "structure_delta": {
                    key: after_counts[key] - before_counts[key] for key in before_counts
                },
            }
        )
        output_parts.append(next_raw + block.get("separator", "\n\n"))

    next_source = prefix + "".join(output_parts)
    return (
        next_source,
        {
            "changed_blocks": changed_blocks,
            "missing_markers": missing_markers,
            "restored_locked_blocks": restored_locked,
        },
    )


def import_page(
    page: dict[str, Any],
    zip_or_dir: Path,
    out_dir: Path,
    *,
    dry_run: bool,
    allow_stale_source: bool,
) -> dict[str, Any]:
    source_path = out_dir / Path(page["source"]).relative_to("content")
    result: dict[str, Any] = {
        "route": page["route"],
        "source": page["source"],
        "docx": page["docx"],
        "status": "unknown",
        "changed": False,
        "errors": [],
    }

    docx_bytes = read_docx_bytes(zip_or_dir, page["docx"])
    if docx_bytes is None:
        result["status"] = "skipped_missing_docx"
        return result

    if not source_path.exists():
        result["status"] = "error"
        result["errors"].append(f"Missing source file: {source_path}")
        return result

    current_source = source_path.read_text(encoding="utf8")
    current_hash = sha256_text(current_source)
    if current_hash != page["source_hash"] and not allow_stale_source:
        result["status"] = "error"
        result["errors"].append(
            f"Stale source: expected {page['source_hash']}, found {current_hash}"
        )
        return result

    imported_blocks = parse_docx_blocks(docx_bytes)
    next_source, page_report = reconstruct_page(page, imported_blocks, current_source)
    result.update(page_report)
    if page_report["missing_markers"]:
        result["status"] = "error"
        result["errors"].append(
            f"Missing block markers: {', '.join(page_report['missing_markers'])}"
        )
        return result

    if next_source == current_source:
        result["status"] = "unchanged"
        return result

    result["changed"] = True
    result["status"] = "changed"
    if not dry_run:
        source_path.write_text(next_source, encoding="utf8")
    return result


def report_path(args: argparse.Namespace, manifest_path: Path) -> Path:
    if args.report:
        return Path(args.report).resolve()
    return manifest_path.parent / "_import-report.json"


def main() -> int:
    args = parse_args()
    zip_or_dir = Path(args.zip).resolve()
    manifest_path = Path(args.manifest).resolve() if args.manifest else default_manifest_path(zip_or_dir)
    out_dir = Path(args.out).resolve()

    manifest = read_manifest(manifest_path)
    page_results = [
        import_page(
            page,
            zip_or_dir,
            out_dir,
            dry_run=args.dry_run,
            allow_stale_source=args.allow_stale_source,
        )
        for page in manifest["pages"]
    ]

    errors = [result for result in page_results if result["status"] == "error"]
    changed = [result for result in page_results if result.get("changed")]
    skipped = [result for result in page_results if result["status"] == "skipped_missing_docx"]

    report = {
        "dry_run": args.dry_run,
        "manifest": str(manifest_path),
        "input": str(zip_or_dir),
        "pages": page_results,
        "summary": {
            "pages": len(page_results),
            "changed": len(changed),
            "unchanged": len([result for result in page_results if result["status"] == "unchanged"]),
            "skipped_missing_docx": len(skipped),
            "errors": len(errors),
        },
    }

    target_report = report_path(args, manifest_path)
    target_report.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf8")

    print(
        "Imported Google Docs review export: "
        f"{len(changed)} changed, {len(skipped)} skipped, {len(errors)} errors."
    )
    print(f"Report: {target_report}")

    if errors:
        for result in errors:
            print(f"- {result['source']}: {'; '.join(result['errors'])}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
